/**
 * data.js
 * -----------------------------------------
 * Datos "crudos" del juego: selecciones, ligas, divisiones y clubes.
 * Acá NO va lógica, solo estructuras de datos.
 * Para agregar contenido nuevo (una selección, una liga, un club) solo
 * hay que tocar este archivo.
 * -----------------------------------------
 * Estructura:
 * PAISES = [ { id, nombre, confederacion, bandera } ]
 * LIGAS_POR_PAIS = { idPais: [ { id, nombre } ] }
 * DIVISIONES_POR_LIGA = { idLiga: [ { id, nombre } ] }
 * CLUBES_POR_DIVISION = { idDivision: [ { id, nombre, escudo } ] }
 *
 * El campo "bandera" (en países) y "escudo" (en clubes) son la ruta
 * o URL a la imagen.
 */

const PAISES = [
  { id: "argentina", nombre: "Argentina", confederacion: "CONMEBOL", bandera: "Selecciones/Argentina.png" },
  { id: "brasil", nombre: "Brasil", confederacion: "CONMEBOL", bandera: "Selecciones/Brasil.png" },
  { id: "uruguay", nombre: "Uruguay", confederacion: "CONMEBOL", bandera: "Selecciones/Uruguay.png" },
  { id: "colombia", nombre: "Colombia", confederacion: "CONMEBOL", bandera: "Selecciones/Colombia.png" },
  { id: "chile", nombre: "Chile", confederacion: "CONMEBOL", bandera: "Selecciones/Chile.png" },
  { id: "ecuador", nombre: "Ecuador", confederacion: "CONMEBOL", bandera: "Selecciones/Ecuador.png" },
  { id: "paraguay", nombre: "Paraguay", confederacion: "CONMEBOL", bandera: "Selecciones/Paraguay.png" },
  { id: "peru", nombre: "Perú", confederacion: "CONMEBOL", bandera: "Selecciones/Peru.png" },
  { id: "bolivia", nombre: "Bolivia", confederacion: "CONMEBOL", bandera: "Selecciones/Bolivia.png" },
  { id: "venezuela", nombre: "Venezuela", confederacion: "CONMEBOL", bandera: "Selecciones/Venezuela.png" },
  { id: "mexico", nombre: "México", confederacion: "CONCACAF", bandera: "Selecciones/Mexico.png" },
  { id: "estados-unidos", nombre: "Estados Unidos", confederacion: "CONCACAF", bandera: "Selecciones/EstadosUnidos.png" },
  { id: "canada", nombre: "Canadá", confederacion: "CONCACAF", bandera: "Selecciones/Canada.png" },
  { id: "costa-rica", nombre: "Costa Rica", confederacion: "CONCACAF", bandera: "Selecciones/CostaRica.png" },
  { id: "panama", nombre: "Panamá", confederacion: "CONCACAF", bandera: "Selecciones/Panama.png" },
  { id: "jamaica", nombre: "Jamaica", confederacion: "CONCACAF", bandera: "Selecciones/Jamaica.png" },
  { id: "honduras", nombre: "Honduras", confederacion: "CONCACAF", bandera: "Selecciones/Honduras.png" },
  { id: "trinidad-y-tobago", nombre: "Trinidad y Tobago", confederacion: "CONCACAF", bandera: "Selecciones/Trinidad.png" },
  { id: "japon", nombre: "Japón", confederacion: "AFC", bandera: "Selecciones/Japon.png" },
  { id: "corea-del-sur", nombre: "Corea del Sur", confederacion: "AFC", bandera: "Selecciones/Corea.png" },
  { id: "iran", nombre: "Irán", confederacion: "AFC", bandera: "Selecciones/Iran.png" },
  { id: "australia", nombre: "Australia", confederacion: "AFC", bandera: "Selecciones/Australia.png" },
  { id: "arabia-saudita", nombre: "Arabia Saudita", confederacion: "AFC", bandera: "Selecciones/Arabia.png" },
  { id: "catar", nombre: "Catar", confederacion: "AFC", bandera: "Selecciones/Catar.png" },
  { id: "uzbekistan", nombre: "Uzbekistán", confederacion: "AFC", bandera: "Selecciones/Uzbekistan.png" },
  { id: "irak", nombre: "Irak", confederacion: "AFC", bandera: "Selecciones/Irak.png" },
  { id: "jordania", nombre: "Jordania", confederacion: "AFC", bandera: "Selecciones/Jordania.png" },
  { id: "indonesia", nombre: "Indonesia", confederacion: "AFC", bandera: "Selecciones/Indonesia.png" },
  { id: "marruecos", nombre: "Marruecos", confederacion: "CAF", bandera: "Selecciones/Marruecos.png" },
  { id: "senegal", nombre: "Senegal", confederacion: "CAF", bandera: "Selecciones/Senegal.png" },
  { id: "egipto", nombre: "Egipto", confederacion: "CAF", bandera: "Selecciones/Egipto.png" },
  { id: "tunez", nombre: "Túnez", confederacion: "CAF", bandera: "Selecciones/Tunez.png" },
  { id: "nigeria", nombre: "Nigeria", confederacion: "CAF", bandera: "Selecciones/Nigeria.png" },
  { id: "ghana", nombre: "Ghana", confederacion: "CAF", bandera: "Selecciones/Ghana.png" },
  { id: "argelia", nombre: "Argelia", confederacion: "CAF", bandera: "Selecciones/Argelia.png" },
  { id: "camerun", nombre: "Camerún", confederacion: "CAF", bandera: "Selecciones/Camerun.png" },
  { id: "sudafrica", nombre: "Sudáfrica", confederacion: "CAF", bandera: "Selecciones/Sudafrica.png" },
  { id: "costa-de-marfil", nombre: "Costa de Marfil", confederacion: "CAF", bandera: "Selecciones/CostaMarfil.png" },
  { id: "nueva-zelanda", nombre: "Nueva Zelanda", confederacion: "OFC", bandera: "Selecciones/NuevaZelanda.png" },
  { id: "alemania", nombre: "Alemania", confederacion: "UEFA", bandera: "Selecciones/Alemania.png" },
  { id: "espana", nombre: "España", confederacion: "UEFA", bandera: "Selecciones/España.png" },
  { id: "francia", nombre: "Francia", confederacion: "UEFA", bandera: "Selecciones/Francia.png" },
  { id: "inglaterra", nombre: "Inglaterra", confederacion: "UEFA", bandera: "Selecciones/Inglaterra.png" },
  { id: "italia", nombre: "Italia", confederacion: "UEFA", bandera: "Selecciones/Italia.png" },
  { id: "portugal", nombre: "Portugal", confederacion: "UEFA", bandera: "Selecciones/Portugal.png" },
  { id: "paises-bajos", nombre: "Países Bajos", confederacion: "UEFA", bandera: "Selecciones/PaisesBajos.png" },
  { id: "belgica", nombre: "Bélgica", confederacion: "UEFA", bandera: "Selecciones/Belgica.png" },
  { id: "croacia", nombre: "Croacia", confederacion: "UEFA", bandera: "Selecciones/Croacia.png" },
  { id: "suiza", nombre: "Suiza", confederacion: "UEFA", bandera: "Selecciones/Suiza.png" },
  { id: "serbia", nombre: "Serbia", confederacion: "UEFA", bandera: "Selecciones/Serbia.png" },
  { id: "dinamarca", nombre: "Dinamarca", confederacion: "UEFA", bandera: "Selecciones/Dinamarca.png" },
  { id: "polonia", nombre: "Polonia", confederacion: "UEFA", bandera: "Selecciones/Polonia.png" },
  { id: "austria", nombre: "Austria", confederacion: "UEFA", bandera: "Selecciones/Austria.png" },
  { id: "suecia", nombre: "Suecia", confederacion: "UEFA", bandera: "Selecciones/Suecia.png" },
  { id: "turquia", nombre: "Turquía", confederacion: "UEFA", bandera: "Selecciones/Turquia.png" },
  { id: "noruega", nombre: "Noruega", confederacion: "UEFA", bandera: "Selecciones/Noruega.png" },
  { id: "escocia", nombre: "Escocia", confederacion: "UEFA", bandera: "Selecciones/Escocia.png" },
  { id: "grecia", nombre: "Grecia", confederacion: "UEFA", bandera: "Selecciones/Grecia.png" },
  { id: "rumania", nombre: "Rumania", confederacion: "UEFA", bandera: "Selecciones/Rumania.png" },
  { id: "bosnia-y-herzegovina", nombre: "Bosnia y Herzegovina", confederacion: "UEFA", bandera: "Selecciones/Bosnia.png" },
  { id: "hungria", nombre: "Hungría", confederacion: "UEFA", bandera: "Selecciones/Hungria.png" },
  { id: "islandia", nombre: "Islandia", confederacion: "UEFA", bandera: "Selecciones/Islandia.png" },
  { id: "gales", nombre: "Gales", confederacion: "UEFA", bandera: "Selecciones/Gales.png" },
];

const LIGAS_POR_PAIS = {
  "argentina": [
    { id: "liga-profesional-argentina", nombre: "Liga Profesional" },
  ],
  "espana": [
    { id: "laliga-espana", nombre: "LaLiga" },
  ],
  "inglaterra": [
    { id: "premier-league-inglaterra", nombre: "Premier League" },
  ],
  "italia": [
    { id: "serie-a-italia", nombre: "Serie A" },
  ],
  "alemania": [
    { id: "bundesliga-alemania", nombre: "Bundesliga" },
  ],
  "francia": [
    { id: "ligue-1-francia", nombre: "Ligue 1" },
  ],
  "brasil": [
    { id: "brasileirao-brasil", nombre: "Brasileirão" },
  ],
  "chile": [
    { id: "primera-division-chile", nombre: "Primera División" },
  ],
  "uruguay": [
    { id: "primera-division-uruguay", nombre: "Primera División" },
  ],
  "mexico": [
    { id: "liga-mx-mexico", nombre: "Liga MX" },
  ],
  "estados-unidos": [
    { id: "mls-estados-unidos", nombre: "MLS" },
  ],
  "arabia-saudita": [
    { id: "saudi-pro-league-arabia-saudita", nombre: "Saudi Pro League" },
  ],
};

const DIVISIONES_POR_LIGA = {
  "liga-profesional-argentina": [
    { id: "primera-division-argentina", nombre: "Primera División" },
    { id: "primera-nacional-argentina", nombre: "Primera Nacional" },
  ],
  "laliga-espana": [
    { id: "primera-division-espana", nombre: "Primera División" },
  ],
  "premier-league-inglaterra": [
    { id: "premier-league-inglaterra", nombre: "Premier League" },
  ],
  "serie-a-italia": [
    { id: "serie-a-italia", nombre: "Serie A" },
  ],
  "bundesliga-alemania": [
    { id: "bundesliga-alemania", nombre: "Bundesliga" },
  ],
  "ligue-1-francia": [
    { id: "ligue-1-francia", nombre: "Ligue 1" },
  ],
  "brasileirao-brasil": [
    { id: "serie-a-brasil", nombre: "Série A" },
  ],
  "primera-division-chile": [
    { id: "primera-division-chile", nombre: "Primera División" },
  ],
  "primera-division-uruguay": [
    { id: "primera-division-uruguay", nombre: "Primera División" },
  ],
  "liga-mx-mexico": [
    { id: "liga-mx-mexico", nombre: "Liga MX" },
  ],
  "mls-estados-unidos": [
    { id: "mls-estados-unidos", nombre: "MLS" },
  ],
  "saudi-pro-league-arabia-saudita": [
    { id: "saudi-pro-league-arabia-saudita", nombre: "Saudi Pro League" },
  ],
};

const CLUBES_POR_DIVISION = {
  "primera-division-argentina": [
    { id: "aldosivi", nombre: "Aldosivi", escudo: "CONMEBOL/Argentina/Aldosivi.png" },
    { id: "argentinos-juniors", nombre: "Argentinos Juniors", escudo: "CONMEBOL/Argentina/Argentinosjrs.png" },
    { id: "atletico-tucuman", nombre: "Atlético Tucumán", escudo: "CONMEBOL/Argentina/AtleticoTucuman.png" },
    { id: "banfield", nombre: "Banfield", escudo: "CONMEBOL/Argentina/Banfield.png" },
    { id: "barracas-central", nombre: "Barracas Central", escudo: "CONMEBOL/Argentina/Barracas.png" },
    { id: "belgrano", nombre: "Belgrano", escudo: "CONMEBOL/Argentina/Belgrano.png" },
    { id: "boca-juniors", nombre: "Boca Juniors", escudo: "CONMEBOL/Argentina/Boca.png" },
    { id: "central-cordoba", nombre: "Central Córdoba", escudo: "CONMEBOL/Argentina/CentralCordoba.png" },
    { id: "defensa-y-justicia", nombre: "Defensa y Justicia", escudo: "CONMEBOL/Argentina/DefensayJusticia.png" },
    { id: "deportivo-riestra", nombre: "Deportivo Riestra", escudo: "CONMEBOL/Argentina/Riestra.png" },
    { id: "estudiantes-lp", nombre: "Estudiantes (LP)", escudo: "CONMEBOL/Argentina/EstudiantesPlata.png" },
    { id: "estudiantes-rc", nombre: "Estudiantes (RC)", escudo: "CONMEBOL/Argentina/EstudiantesRioCuarto.png" },
    { id: "gimnasia-lp", nombre: "Gimnasia y Esgrima (LP)", escudo: "CONMEBOL/Argentina/GimnasiayEsgrima.png" },
    { id: "gimnasia-m", nombre: "Gimnasia y Esgrima (M)", escudo: "CONMEBOL/Argentina/GimnasiaMendoza.png" },
    { id: "huracan", nombre: "Huracán", escudo: "CONMEBOL/Argentina/Huracan.png" },
    { id: "independiente", nombre: "Independiente", escudo: "CONMEBOL/Argentina/Independiente.png" },
    { id: "independiente-rivadavia", nombre: "Independiente Rivadavia", escudo: "CONMEBOL/Argentina/IndependienteRivadavia.png" },
    { id: "instituto", nombre: "Instituto", escudo: "CONMEBOL/Argentina/InstitutoCordoba.png" },
    { id: "lanus", nombre: "Lanús", escudo: "CONMEBOL/Argentina/Lanus.png" },
    { id: "newells", nombre: "Newell's Old Boys", escudo: "CONMEBOL/Argentina/Newells.png" },
    { id: "platense", nombre: "Platense", escudo: "CONMEBOL/Argentina/Platense.png" },
    { id: "racing-club", nombre: "Racing Club", escudo: "CONMEBOL/Argentina/Racing.png" },
    { id: "river-plate", nombre: "River Plate", escudo: "CONMEBOL/Argentina/River.png" },
    { id: "rosario-central", nombre: "Rosario Central", escudo: "CONMEBOL/Argentina/RosarioCentral.png" },
    { id: "san-lorenzo", nombre: "San Lorenzo", escudo: "CONMEBOL/Argentina/SanLorenzo.png" },
    { id: "sarmiento", nombre: "Sarmiento", escudo: "CONMEBOL/Argentina/SarmientoJunin.png" },
    { id: "talleres", nombre: "Talleres", escudo: "CONMEBOL/Argentina/Talleres.png" },
    { id: "tigre", nombre: "Tigre", escudo: "CONMEBOL/Argentina/Tigre.png" },
    { id: "union", nombre: "Unión", escudo: "CONMEBOL/Argentina/UnionSantaFe.png" },
    { id: "velez-sarsfield", nombre: "Vélez Sarsfield", escudo: "CONMEBOL/Argentina/Velez.png" },
  ],
  "primera-division-espana": [
    { id: "alaves", nombre: "Alavés", escudo: "" },
    { id: "athletic-bilbao", nombre: "Athletic Bilbao", escudo: "" },
    { id: "atletico-madrid", nombre: "Atlético Madrid", escudo: "" },
    { id: "barcelona", nombre: "Barcelona", escudo: "" },
    { id: "celta-vigo", nombre: "Celta Vigo", escudo: "" },
    { id: "deportivo-la-coruna", nombre: "Deportivo La Coruña", escudo: "" },
    { id: "elche", nombre: "Elche", escudo: "" },
    { id: "espanyol", nombre: "Espanyol", escudo: "" },
    { id: "getafe", nombre: "Getafe", escudo: "" },
    { id: "levante", nombre: "Levante", escudo: "" },
    { id: "malaga", nombre: "Málaga", escudo: "" },
    { id: "osasuna", nombre: "Osasuna", escudo: "" },
    { id: "racing-santander", nombre: "Racing Santander", escudo: "" },
    { id: "rayo-vallecano", nombre: "Rayo Vallecano", escudo: "" },
    { id: "real-betis", nombre: "Real Betis", escudo: "" },
    { id: "real-madrid", nombre: "Real Madrid", escudo: "" },
    { id: "real-sociedad", nombre: "Real Sociedad", escudo: "" },
    { id: "sevilla", nombre: "Sevilla", escudo: "" },
    { id: "valencia", nombre: "Valencia", escudo: "" },
    { id: "villarreal", nombre: "Villarreal", escudo: "" },
  ],
  "premier-league-inglaterra": [
    { id: "arsenal", nombre: "Arsenal", escudo: "" },
    { id: "aston-villa", nombre: "Aston Villa", escudo: "" },
    { id: "bournemouth", nombre: "Bournemouth", escudo: "" },
    { id: "brentford", nombre: "Brentford", escudo: "" },
    { id: "brighton", nombre: "Brighton", escudo: "" },
    { id: "chelsea", nombre: "Chelsea", escudo: "" },
    { id: "coventry-city", nombre: "Coventry City", escudo: "" },
    { id: "crystal-palace", nombre: "Crystal Palace", escudo: "" },
    { id: "everton", nombre: "Everton", escudo: "" },
    { id: "fulham", nombre: "Fulham", escudo: "" },
    { id: "hull-city", nombre: "Hull City", escudo: "" },
    { id: "ipswich-town", nombre: "Ipswich Town", escudo: "" },
    { id: "leeds-united", nombre: "Leeds United", escudo: "" },
    { id: "liverpool", nombre: "Liverpool", escudo: "" },
    { id: "manchester-city", nombre: "Manchester City", escudo: "" },
    { id: "manchester-united", nombre: "Manchester United", escudo: "" },
    { id: "newcastle", nombre: "Newcastle", escudo: "" },
    { id: "nottingham-forest", nombre: "Nottingham Forest", escudo: "" },
    { id: "sunderland", nombre: "Sunderland", escudo: "" },
    { id: "tottenham", nombre: "Tottenham", escudo: "" },
  ],
  "serie-a-italia": [
    { id: "atalanta", nombre: "Atalanta", escudo: "" },
    { id: "bologna", nombre: "Bologna", escudo: "" },
    { id: "cagliari", nombre: "Cagliari", escudo: "" },
    { id: "como", nombre: "Como", escudo: "" },
    { id: "fiorentina", nombre: "Fiorentina", escudo: "" },
    { id: "frosinone", nombre: "Frosinone", escudo: "" },
    { id: "genoa", nombre: "Genoa", escudo: "" },
    { id: "inter", nombre: "Inter", escudo: "" },
    { id: "juventus", nombre: "Juventus", escudo: "" },
    { id: "lazio", nombre: "Lazio", escudo: "" },
    { id: "lecce", nombre: "Lecce", escudo: "" },
    { id: "milan", nombre: "Milan", escudo: "" },
    { id: "monza", nombre: "Monza", escudo: "" },
    { id: "napoli", nombre: "Napoli", escudo: "" },
    { id: "parma", nombre: "Parma", escudo: "" },
    { id: "roma", nombre: "Roma", escudo: "" },
    { id: "sassuolo", nombre: "Sassuolo", escudo: "" },
    { id: "torino", nombre: "Torino", escudo: "" },
    { id: "udinese", nombre: "Udinese", escudo: "" },
    { id: "venezia", nombre: "Venezia", escudo: "" },
  ],
  "bundesliga-alemania": [
    { id: "augsburg", nombre: "Augsburg", escudo: "" },
    { id: "bayern-munich", nombre: "Bayern Múnich", escudo: "" },
    { id: "bayer-leverkusen", nombre: "Bayer Leverkusen", escudo: "" },
    { id: "borussia-dortmund", nombre: "Borussia Dortmund", escudo: "" },
    { id: "borussia-monchengladbach", nombre: "Borussia Mönchengladbach", escudo: "" },
    { id: "colonia", nombre: "Colonia", escudo: "" },
    { id: "eintracht-francfort", nombre: "Eintracht Fráncfort", escudo: "" },
    { id: "elversberg", nombre: "Elversberg", escudo: "" },
    { id: "friburgo", nombre: "Friburgo", escudo: "" },
    { id: "hamburgo", nombre: "Hamburgo", escudo: "" },
    { id: "hoffenheim", nombre: "Hoffenheim", escudo: "" },
    { id: "mainz-05", nombre: "Mainz 05", escudo: "" },
    { id: "paderborn", nombre: "Paderborn", escudo: "" },
    { id: "rb-leipzig", nombre: "RB Leipzig", escudo: "" },
    { id: "schalke-04", nombre: "Schalke 04", escudo: "" },
    { id: "stuttgart", nombre: "Stuttgart", escudo: "" },
    { id: "union-berlin", nombre: "Union Berlín", escudo: "" },
    { id: "werder-bremen", nombre: "Werder Bremen", escudo: "" },
  ],
  "ligue-1-francia": [
    { id: "angers", nombre: "Angers", escudo: "" },
    { id: "auxerre", nombre: "Auxerre", escudo: "" },
    { id: "brest", nombre: "Brest", escudo: "" },
    { id: "estrasburgo", nombre: "Estrasburgo", escudo: "" },
    { id: "le-havre", nombre: "Le Havre", escudo: "" },
    { id: "le-mans", nombre: "Le Mans", escudo: "" },
    { id: "lens", nombre: "Lens", escudo: "" },
    { id: "lille", nombre: "Lille", escudo: "" },
    { id: "lorient", nombre: "Lorient", escudo: "" },
    { id: "lyon", nombre: "Lyon", escudo: "" },
    { id: "marsella", nombre: "Marsella", escudo: "" },
    { id: "monaco", nombre: "Mónaco", escudo: "" },
    { id: "niza", nombre: "Niza", escudo: "" },
    { id: "paris-fc", nombre: "París FC", escudo: "" },
    { id: "psg", nombre: "PSG", escudo: "" },
    { id: "rennes", nombre: "Rennes", escudo: "" },
    { id: "toulouse", nombre: "Toulouse", escudo: "" },
    { id: "troyes", nombre: "Troyes", escudo: "" },
  ],
  "serie-a-brasil": [
    { id: "athletico-paranaense", nombre: "Athletico Paranaense", escudo: "CONMEBOL/Brasil/Paranaense.png" },
    { id: "atletico-mineiro", nombre: "Atlético Mineiro", escudo: "CONMEBOL/Brasil/Mineiro.png" },
    { id: "bahia", nombre: "Bahia", escudo: "CONMEBOL/Brasil/Bahia.png" },
    { id: "botafogo", nombre: "Botafogo", escudo: "CONMEBOL/Brasil/Botafogo.png" },
    { id: "bragantino", nombre: "Bragantino", escudo: "CONMEBOL/Brasil/Bragantino.png" },
    { id: "chapecoense", nombre: "Chapecoense", escudo: "CONMEBOL/Brasil/Chapecoense.png" },
    { id: "corinthians", nombre: "Corinthians", escudo: "CONMEBOL/Brasil/Corinthians.png" },
    { id: "coritiba", nombre: "Coritiba", escudo: "CONMEBOL/Brasil/Coritiba.png" },
    { id: "cruzeiro", nombre: "Cruzeiro", escudo: "CONMEBOL/Brasil/Cruzeiro.png" },
    { id: "flamengo", nombre: "Flamengo", escudo: "CONMEBOL/Brasil/Flamengo.png" },
    { id: "fluminense", nombre: "Fluminense", escudo: "CONMEBOL/Brasil/Fluminense.png" },
    { id: "gremio", nombre: "Grêmio", escudo: "CONMEBOL/Brasil/Gremio.png" },
    { id: "internacional", nombre: "Internacional", escudo: "CONMEBOL/Brasil/Internacional.png" },
    { id: "mirassol", nombre: "Mirassol", escudo: "CONMEBOL/Brasil/Mirassol.png" },
    { id: "palmeiras", nombre: "Palmeiras", escudo: "CONMEBOL/Brasil/Palmeiras.png" },
    { id: "remo", nombre: "Remo", escudo: "CONMEBOL/Brasil/Remo.png" },
    { id: "santos", nombre: "Santos", escudo: "CONMEBOL/Brasil/Santos.png" },
    { id: "sao-paulo", nombre: "São Paulo", escudo: "CONMEBOL/Brasil/SaoPaulo.png" },
    { id: "vasco-da-gama", nombre: "Vasco da Gama", escudo: "CONMEBOL/Brasil/Vasco.png" },
    { id: "vitoria", nombre: "Vitória", escudo: "CONMEBOL/Brasil/Vitoria.png" },
  ],
  "primera-division-chile": [
    { id: "colo-colo", nombre: "Colo-Colo", escudo: "" },
    { id: "universidad-de-chile", nombre: "Universidad de Chile", escudo: "" },
    { id: "universidad-catolica", nombre: "Universidad Católica", escudo: "" },
    { id: "coquimbo-unido", nombre: "Coquimbo Unido", escudo: "" },
    { id: "everton-2", nombre: "Everton", escudo: "" },
    { id: "nublense", nombre: "Ñublense", escudo: "" },
    { id: "union-la-calera", nombre: "Unión La Calera", escudo: "" },
    { id: "ohiggins", nombre: "O'Higgins", escudo: "" },
    { id: "palestino", nombre: "Palestino", escudo: "" },
    { id: "huachipato", nombre: "Huachipato", escudo: "" },
    { id: "audax-italiano", nombre: "Audax Italiano", escudo: "" },
    { id: "deportes-iquique", nombre: "Deportes Iquique", escudo: "" },
    { id: "cobresal", nombre: "Cobresal", escudo: "" },
    { id: "union-espanola", nombre: "Unión Española", escudo: "" },
    { id: "deportes-copiapo", nombre: "Deportes Copiapó", escudo: "" },
    { id: "rangers", nombre: "Rangers", escudo: "" },
  ],
  "primera-division-uruguay": [
    { id: "penarol", nombre: "Peñarol", escudo: "" },
    { id: "nacional", nombre: "Nacional", escudo: "" },
    { id: "danubio", nombre: "Danubio", escudo: "" },
    { id: "wanderers", nombre: "Wanderers", escudo: "" },
    { id: "liverpool-2", nombre: "Liverpool", escudo: "" },
    { id: "cerro-largo", nombre: "Cerro Largo", escudo: "" },
    { id: "defensor-sporting", nombre: "Defensor Sporting", escudo: "" },
    { id: "river-plate-2", nombre: "River Plate", escudo: "" },
    { id: "boston-river", nombre: "Boston River", escudo: "" },
    { id: "montevideo-city-torque", nombre: "Montevideo City Torque", escudo: "" },
    { id: "plaza-colonia", nombre: "Plaza Colonia", escudo: "" },
    { id: "progreso", nombre: "Progreso", escudo: "" },
    { id: "sud-america", nombre: "Sud América", escudo: "" },
    { id: "miramar-misiones", nombre: "Miramar Misiones", escudo: "" },
    { id: "racing", nombre: "Racing", escudo: "" },
    { id: "juventud", nombre: "Juventud", escudo: "" },
  ],
  "liga-mx-mexico": [
    { id: "america", nombre: "América", escudo: "" },
    { id: "atletico-san-luis", nombre: "Atlético San Luis", escudo: "" },
    { id: "chivas-guadalajara", nombre: "Chivas (Guadalajara)", escudo: "" },
    { id: "cruz-azul", nombre: "Cruz Azul", escudo: "" },
    { id: "juarez", nombre: "Juárez", escudo: "" },
    { id: "leon", nombre: "León", escudo: "" },
    { id: "mazatlan", nombre: "Mazatlán", escudo: "" },
    { id: "monterrey", nombre: "Monterrey", escudo: "" },
    { id: "necaxa", nombre: "Necaxa", escudo: "" },
    { id: "pachuca", nombre: "Pachuca", escudo: "" },
    { id: "puebla", nombre: "Puebla", escudo: "" },
    { id: "pumas-unam", nombre: "Pumas UNAM", escudo: "" },
    { id: "queretaro", nombre: "Querétaro", escudo: "" },
    { id: "santos-laguna", nombre: "Santos Laguna", escudo: "" },
    { id: "tijuana", nombre: "Tijuana", escudo: "" },
    { id: "tigres-uanl", nombre: "Tigres UANL", escudo: "" },
    { id: "toluca", nombre: "Toluca", escudo: "" },
    { id: "tlaxcala", nombre: "Tlaxcala", escudo: "" },
  ],
  "mls-estados-unidos": [
    { id: "atlanta-united", nombre: "Atlanta United", escudo: "" },
    { id: "austin-fc", nombre: "Austin FC", escudo: "" },
    { id: "charlotte-fc", nombre: "Charlotte FC", escudo: "" },
    { id: "chicago-fire", nombre: "Chicago Fire", escudo: "" },
    { id: "colorado-rapids", nombre: "Colorado Rapids", escudo: "" },
    { id: "columbus-crew", nombre: "Columbus Crew", escudo: "" },
    { id: "dc-united", nombre: "DC United", escudo: "" },
    { id: "fc-cincinnati", nombre: "FC Cincinnati", escudo: "" },
    { id: "fc-dallas", nombre: "FC Dallas", escudo: "" },
    { id: "houston-dynamo", nombre: "Houston Dynamo", escudo: "" },
    { id: "inter-miami", nombre: "Inter Miami", escudo: "" },
    { id: "lafc", nombre: "LAFC", escudo: "" },
    { id: "la-galaxy", nombre: "LA Galaxy", escudo: "" },
    { id: "minnesota-united", nombre: "Minnesota United", escudo: "" },
    { id: "cf-montreal", nombre: "CF Montréal", escudo: "" },
    { id: "nashville-sc", nombre: "Nashville SC", escudo: "" },
    { id: "new-england-revolution", nombre: "New England Revolution", escudo: "" },
    { id: "new-york-city", nombre: "New York City", escudo: "" },
    { id: "new-york-red-bulls", nombre: "New York Red Bulls", escudo: "" },
    { id: "orlando-city", nombre: "Orlando City", escudo: "" },
    { id: "philadelphia-union", nombre: "Philadelphia Union", escudo: "" },
    { id: "portland-timbers", nombre: "Portland Timbers", escudo: "" },
    { id: "real-salt-lake", nombre: "Real Salt Lake", escudo: "" },
    { id: "san-diego-fc", nombre: "San Diego FC", escudo: "" },
    { id: "san-jose-earthquakes", nombre: "San José Earthquakes", escudo: "" },
    { id: "seattle-sounders", nombre: "Seattle Sounders", escudo: "" },
    { id: "sporting-kansas-city", nombre: "Sporting Kansas City", escudo: "" },
    { id: "st-louis-city", nombre: "St. Louis City", escudo: "" },
    { id: "toronto-fc", nombre: "Toronto FC", escudo: "" },
    { id: "vancouver-whitecaps", nombre: "Vancouver Whitecaps", escudo: "" },
  ],
  "saudi-pro-league-arabia-saudita": [
    { id: "al-hilal", nombre: "Al-Hilal", escudo: "" },
    { id: "al-ahli", nombre: "Al-Ahli", escudo: "" },
    { id: "al-ittihad", nombre: "Al-Ittihad", escudo: "" },
    { id: "al-nassr", nombre: "Al-Nassr", escudo: "" },
    { id: "al-qadsiah", nombre: "Al-Qadsiah", escudo: "" },
    { id: "neom", nombre: "NEOM", escudo: "" },
    { id: "al-shabab", nombre: "Al-Shabab", escudo: "" },
    { id: "al-taawoun", nombre: "Al-Taawoun", escudo: "" },
    { id: "al-ettifaq", nombre: "Al-Ettifaq", escudo: "" },
    { id: "al-kholood", nombre: "Al-Kholood", escudo: "" },
    { id: "al-fateh", nombre: "Al-Fateh", escudo: "" },
    { id: "al-fayha", nombre: "Al-Fayha", escudo: "" },
    { id: "al-najma", nombre: "Al-Najma", escudo: "" },
    { id: "al-okhdood", nombre: "Al-Okhdood", escudo: "" },
    { id: "al-riyadh", nombre: "Al-Riyadh", escudo: "" },
    { id: "al-khaleej", nombre: "Al-Khaleej", escudo: "" },
    { id: "al-hazem", nombre: "Al-Hazem", escudo: "" },
    { id: "damac", nombre: "Damac", escudo: "" },
  ],
};

/**
 * ESCUDOS Y BANDERAS
 * -----------------------------------------
 * No hace falta ninguna función acá: cada país tiene su campo "bandera"
 * y cada club tiene su campo "escudo", con la ruta o URL que vos les pongas.
 * El menú las usa directamente tal cual las escribiste.
 */