/**
 * data.js
 * -----------------------------------------
 * Datos "crudos" del juego: selecciones, ligas, divisiones y clubes.
 * Acá NO va lógica, solo estructuras de datos.
 * -----------------------------------------
 */

const PAISES = [
  { id: "argentina", nombre: "Argentina", confederacion: "CONMEBOL", bandera: "Selecciones/Argentina.png" },
  { id: "brasil", nombre: "Brasil", confederacion: "CONMEBOL", bandera: "Selecciones/Brasil.png" },
  { id: "uruguay", nombre: "Uruguay", confederacion: "CONMEBOL", bandera: "Selecciones/Uruguay.png" },
  { id: "colombia", nombre: "Colombia", confederacion: "CONMEBOL", bandera: "Selecciones/Colombia.png" },
  { id: "chile", nombre: "Chile", confederacion: "CONMEBOL", bandera: "Selecciones/Chile.png" },
  { id: "ecuador", nombre: "Ecuador", confederacion: "CONMEBOL", bandera: "Selecciones/Ecuador.png" },
  { id: "paraguay", nombre: "Paraguay", confederacion: "CONMEBOL", bandera: "Selecciones/Paraguay.png" },
  { id: "peru", nombre: "Perú", confederacion: "CONMEBOL", bandera: "Selecciones/Peru.png" },
  { id: "bolivia", nombre: "Bolivia", confederacion: "CONMEBOL", bandera: "Selecciones/Bolivia.png" },
  { id: "venezuela", nombre: "Venezuela", confederacion: "CONMEBOL", bandera: "Selecciones/Venezuela.png" },
  { id: "mexico", nombre: "México", confederacion: "CONCACAF", bandera: "Selecciones/Mexico.png" },
  { id: "estados-unidos", nombre: "Estados Unidos", confederacion: "CONCACAF", bandera: "Selecciones/EstadosUnidos.png" },
  { id: "canada", nombre: "Canadá", confederacion: "CONCACAF", bandera: "Selecciones/Canada.png" },
  { id: "costa-rica", nombre: "Costa Rica", confederacion: "CONCACAF", bandera: "Selecciones/CostaRica.png" },
  { id: "panama", nombre: "Panamá", confederacion: "CONCACAF", bandera: "Selecciones/Panama.png" },
  { id: "jamaica", nombre: "Jamaica", confederacion: "CONCACAF", bandera: "Selecciones/Jamaica.png" },
  { id: "honduras", nombre: "Honduras", confederacion: "CONCACAF", bandera: "Selecciones/Honduras.png" },
  { id: "trinidad-y-tobago", nombre: "Trinidad y Tobago", confederacion: "CONCACAF", bandera: "Selecciones/Trinidad.png" },
  { id: "japon", nombre: "Japón", confederacion: "AFC", bandera: "Selecciones/Japon.png" },
  { id: "corea-del-sur", nombre: "Corea del Sur", confederacion: "AFC", bandera: "Selecciones/Corea.png" },
  { id: "iran", nombre: "Irán", confederacion: "AFC", bandera: "Selecciones/Iran.png" },
  { id: "australia", nombre: "Australia", confederacion: "AFC", bandera: "Selecciones/Australia.png" },
  { id: "arabia-saudita", nombre: "Arabia Saudita", confederacion: "AFC", bandera: "Selecciones/Arabia.png" },
  { id: "catar", nombre: "Catar", confederacion: "AFC", bandera: "Selecciones/Catar.png" },
  { id: "uzbekistan", nombre: "Uzbekistán", confederacion: "AFC", bandera: "Selecciones/Uzbekistan.png" },
  { id: "irak", nombre: "Irak", confederacion: "AFC", bandera: "Selecciones/Irak.png" },
  { id: "jordania", nombre: "Jordania", confederacion: "AFC", bandera: "Selecciones/Jordania.png" },
  { id: "indonesia", nombre: "Indonesia", confederacion: "AFC", bandera: "Selecciones/Indonesia.png" },
  { id: "marruecos", nombre: "Marruecos", confederacion: "CAF", bandera: "Selecciones/Marruecos.png" },
  { id: "senegal", nombre: "Senegal", confederacion: "CAF", bandera: "Selecciones/Senegal.png" },
  { id: "egipto", nombre: "Egipto", confederacion: "CAF", bandera: "Selecciones/Egipto.png" },
  { id: "tunez", nombre: "Túnez", confederacion: "CAF", bandera: "Selecciones/Tunez.png" },
  { id: "nigeria", nombre: "Nigeria", confederacion: "CAF", bandera: "Selecciones/Nigeria.png" },
  { id: "ghana", nombre: "Ghana", confederacion: "CAF", bandera: "Selecciones/Ghana.png" },
  { id: "argelia", nombre: "Argelia", confederacion: "CAF", bandera: "Selecciones/Argelia.png" },
  { id: "camerun", nombre: "Camerún", confederacion: "CAF", bandera: "Selecciones/Camerun.png" },
  { id: "sudafrica", nombre: "Sudáfrica", confederacion: "CAF", bandera: "Selecciones/Sudafrica.png" },
  { id: "costa-de-marfil", nombre: "Costa de Marfil", confederacion: "CAF", bandera: "Selecciones/CostaMarfil.png" },
  { id: "nueva-zelanda", nombre: "Nueva Zelanda", confederacion: "OFC", bandera: "Selecciones/NuevaZelanda.png" },
  { id: "alemania", nombre: "Alemania", confederacion: "UEFA", bandera: "Selecciones/Alemania.png" },
  { id: "espana", nombre: "España", confederacion: "UEFA", bandera: "Selecciones/España.png" },
  { id: "francia", nombre: "Francia", confederacion: "UEFA", bandera: "Selecciones/Francia.png" },
  { id: "inglaterra", nombre: "Inglaterra", confederacion: "UEFA", bandera: "Selecciones/Inglaterra.png" },
  { id: "italia", nombre: "Italia", confederacion: "UEFA", bandera: "Selecciones/Italia.png" },
  { id: "portugal", nombre: "Portugal", confederacion: "UEFA", bandera: "Selecciones/Portugal.png" },
  { id: "paises-bajos", nombre: "Países Bajos", confederacion: "UEFA", bandera: "Selecciones/PaisesBajos.png" },
  { id: "belgica", nombre: "Bélgica", confederacion: "UEFA", bandera: "Selecciones/Belgica.png" },
  { id: "croacia", nombre: "Croacia", confederacion: "UEFA", bandera: "Selecciones/Croacia.png" },
  { id: "suiza", nombre: "Suiza", confederacion: "UEFA", bandera: "Selecciones/Suiza.png" },
  { id: "serbia", nombre: "Serbia", confederacion: "UEFA", bandera: "Selecciones/Serbia.png" },
  { id: "dinamarca", nombre: "Dinamarca", confederacion: "UEFA", bandera: "Selecciones/Dinamarca.png" },
  { id: "polonia", nombre: "Polonia", confederacion: "UEFA", bandera: "Selecciones/Polonia.png" },
  { id: "austria", nombre: "Austria", confederacion: "UEFA", bandera: "Selecciones/Austria.png" },
  { id: "suecia", nombre: "Suecia", confederacion: "UEFA", bandera: "Selecciones/Suecia.png" },
  { id: "turquia", nombre: "Turquía", confederacion: "UEFA", bandera: "Selecciones/Turquia.png" },
  { id: "noruega", nombre: "Noruega", confederacion: "UEFA", bandera: "Selecciones/Noruega.png" },
  { id: "escocia", nombre: "Escocia", confederacion: "UEFA", bandera: "Selecciones/Escocia.png" },
  { id: "grecia", nombre: "Grecia", confederacion: "UEFA", bandera: "Selecciones/Grecia.png" },
  { id: "rumania", nombre: "Rumania", confederacion: "UEFA", bandera: "Selecciones/Rumania.png" },
  { id: "bosnia-y-herzegovina", nombre: "Bosnia y Herzegovina", confederacion: "UEFA", bandera: "Selecciones/Bosnia.png" },
  { id: "hungria", nombre: "Hungría", confederacion: "UEFA", bandera: "Selecciones/Hungria.png" },
  { id: "islandia", nombre: "Islandia", confederacion: "UEFA", bandera: "Selecciones/Islandia.png" },
  { id: "gales", nombre: "Gales", confederacion: "UEFA", bandera: "Selecciones/Gales.png" },
];

const LIGAS_POR_PAIS = {
  "argentina": [
    { id: "liga-profesional-argentina", nombre: "Liga Profesional" },
  ],
  "brasil": [
    { id: "brasileirao-brasil", nombre: "Brasileirão" },
  ],
  "alemania": [
    { id: "bundesliga-alemania", nombre: "Bundesliga" },
  ],
  "espana": [
    { id: "laliga-espana", nombre: "LaLiga" },
  ],
  "italia": [
    { id: "serie-a-italia", nombre: "Serie A" },
  ],
  "francia": [
    { id: "ligue-1-francia", nombre: "Ligue 1" },
  ],
  "inglaterra": [
    { id: "premier-league-inglaterra", nombre: "Premier League" },
  ]
};

const DIVISIONES_POR_LIGA = {
  "liga-profesional-argentina": [
    { id: "primera-division-argentina", nombre: "Primera División" },
    { id: "primera-nacional-argentina", nombre: "Primera Nacional" },
  ],
  "brasileirao-brasil": [
    { id: "serie-a-brasil", nombre: "Série A" },
  ],
  "bundesliga-alemania": [
    { id: "bundesliga-alemania", nombre: "Bundesliga" },
  ],
  "laliga-espana": [
    { id: "primera-division-espana", nombre: "Primera División" },
  ],
  "serie-a-italia": [
    { id: "serie-a-italia", nombre: "Serie A" },
  ],
  "ligue-1-francia": [
    { id: "ligue-1-francia", nombre: "Ligue 1" },
  ],
  "premier-league-inglaterra": [
    { id: "premier-league-inglaterra", nombre: "Premier League" },
  ]
};

const CLUBES_POR_DIVISION = {
  "primera-division-argentina": [
    { id: "aldosivi", nombre: "Aldosivi", escudo: "CONMEBOL/Argentina/Aldosivi.png" },
    { id: "argentinos-juniors", nombre: "Argentinos Juniors", escudo: "CONMEBOL/Argentina/Argentinosjrs.png" },
    { id: "atletico-tucuman", nombre: "Atlético Tucumán", escudo: "CONMEBOL/Argentina/AtleticoTucuman.png" },
    { id: "banfield", nombre: "Banfield", escudo: "CONMEBOL/Argentina/Banfield.png" },
    { id: "barracas-central", nombre: "Barracas Central", escudo: "CONMEBOL/Argentina/Barracas.png" },
    { id: "belgrano", nombre: "Belgrano", escudo: "CONMEBOL/Argentina/Belgrano.png" },
    { id: "boca-juniors", nombre: "Boca Juniors", escudo: "CONMEBOL/Argentina/Boca.png" },
    { id: "central-cordoba", nombre: "Central Córdoba", escudo: "CONMEBOL/Argentina/CentralCordoba.png" },
    { id: "defensa-y-justicia", nombre: "Defensa y Justicia", escudo: "CONMEBOL/Argentina/DefensayJusticia.png" },
    { id: "deportivo-riestra", nombre: "Deportivo Riestra", escudo: "CONMEBOL/Argentina/Riestra.png" },
    { id: "estudiantes-lp", nombre: "Estudiantes (LP)", escudo: "CONMEBOL/Argentina/EstudiantesPlata.png" },
    { id: "estudiantes-rc", nombre: "Estudiantes (RC)", escudo: "CONMEBOL/Argentina/EstudiantesRioCuarto.png" },
    { id: "gimnasia-lp", nombre: "Gimnasia y Esgrima (LP)", escudo: "CONMEBOL/Argentina/GimnasiayEsgrima.png" },
    { id: "gimnasia-m", nombre: "Gimnasia y Esgrima (M)", escudo: "CONMEBOL/Argentina/GimnasiaMendoza.png" },
    { id: "huracan", nombre: "Huracán", escudo: "CONMEBOL/Argentina/Huracan.png" },
    { id: "independiente", nombre: "Independiente", escudo: "CONMEBOL/Argentina/Independiente.png" },
    { id: "independiente-rivadavia", nombre: "Independiente Rivadavia", escudo: "CONMEBOL/Argentina/IndependienteRivadavia.png" },
    { id: "instituto", nombre: "Instituto", escudo: "CONMEBOL/Argentina/InstitutoCordoba.png" },
    { id: "lanus", nombre: "Lanús", escudo: "CONMEBOL/Argentina/Lanus.png" },
    { id: "newells", nombre: "Newell's Old Boys", escudo: "CONMEBOL/Argentina/Newells.png" },
    { id: "platense", nombre: "Platense", escudo: "CONMEBOL/Argentina/Platense.png" },
    { id: "racing-club", nombre: "Racing Club", escudo: "CONMEBOL/Argentina/Racing.png" },
    { id: "river-plate", nombre: "River Plate", escudo: "CONMEBOL/Argentina/River.png" },
    { id: "rosario-central", nombre: "Rosario Central", escudo: "CONMEBOL/Argentina/RosarioCentral.png" },
    { id: "san-lorenzo", nombre: "San Lorenzo", escudo: "CONMEBOL/Argentina/SanLorenzo.png" },
    { id: "sarmiento", nombre: "Sarmiento", escudo: "CONMEBOL/Argentina/SarmientoJunin.png" },
    { id: "talleres", nombre: "Talleres", escudo: "CONMEBOL/Argentina/Talleres.png" },
    { id: "tigre", nombre: "Tigre", escudo: "CONMEBOL/Argentina/Tigre.png" },
    { id: "union", nombre: "Unión", escudo: "CONMEBOL/Argentina/UnionSantaFe.png" },
    { id: "velez-sarsfield", nombre: "Vélez Sarsfield", escudo: "CONMEBOL/Argentina/Velez.png" },
  ],
  "serie-a-brasil": [
    { id: "athletico-paranaense", nombre: "Athletico Paranaense", escudo: "CONMEBOL/Brasil/Paranaense.png" },
    { id: "atletico-mineiro", nombre: "Atlético Mineiro", escudo: "CONMEBOL/Brasil/Mineiro.png" },
    { id: "bahia", nombre: "Bahia", escudo: "CONMEBOL/Brasil/Bahia.png" },
    { id: "botafogo", nombre: "Botafogo", escudo: "CONMEBOL/Brasil/Botafogo.png" },
    { id: "bragantino", nombre: "Bragantino", escudo: "CONMEBOL/Brasil/Bragantino.png" },
    { id: "chapecoense", nombre: "Chapecoense", escudo: "CONMEBOL/Brasil/Chapecoense.png" },
    { id: "corinthians", nombre: "Corinthians", escudo: "CONMEBOL/Brasil/Corinthians.png" },
    { id: "coritiba", nombre: "Coritiba", escudo: "CONMEBOL/Brasil/Coritiba.png" },
    { id: "cruzeiro", nombre: "Cruzeiro", escudo: "CONMEBOL/Brasil/Cruzeiro.png" },
    { id: "flamengo", nombre: "Flamengo", escudo: "CONMEBOL/Brasil/Flamengo.png" },
    { id: "fluminense", nombre: "Fluminense", escudo: "CONMEBOL/Brasil/Fluminense.png" },
    { id: "gremio", nombre: "Grêmio", escudo: "CONMEBOL/Brasil/Gremio.png" },
    { id: "internacional", nombre: "Internacional", escudo: "CONMEBOL/Brasil/Internacional.png" },
    { id: "mirassol", nombre: "Mirassol", escudo: "CONMEBOL/Brasil/Mirassol.png" },
    { id: "palmeiras", nombre: "Palmeiras", escudo: "CONMEBOL/Brasil/Palmeiras.png" },
    { id: "remo", nombre: "Remo", escudo: "CONMEBOL/Brasil/Remo.png" },
    { id: "santos", nombre: "Santos", escudo: "CONMEBOL/Brasil/Santos.png" },
    { id: "sao-paulo", nombre: "São Paulo", escudo: "CONMEBOL/Brasil/SaoPaulo.png" },
    { id: "vasco-da-gama", nombre: "Vasco da Gama", escudo: "CONMEBOL/Brasil/Vasco.png" },
    { id: "vitoria", nombre: "Vitória", escudo: "CONMEBOL/Brasil/Vitoria.png" },
  ],
  "bundesliga-alemania": [
    { id: "augsburg", nombre: "Augsburg", escudo: "UEFA/Alemania/Augsburg.png" },
    { id: "bayern-munich", nombre: "Bayern Múnich", escudo: "UEFA/Alemania/Bayern.png" },
    { id: "bayer-leverkusen", nombre: "Bayer Leverkusen", escudo: "UEFA/Alemania/Leverkusen.png" },
    { id: "borussia-dortmund", nombre: "Borussia Dortmund", escudo: "UEFA/Alemania/Borussia.png" },
    { id: "borussia-monchengladbach", nombre: "Borussia Mönchengladbach", escudo: "UEFA/Alemania/BorussiaMonchen.png" },
    { id: "colonia", nombre: "Colonia", escudo: "UEFA/Alemania/Cologne.png" },
    { id: "eintracht-francfort", nombre: "Eintracht Fráncfort", escudo: "UEFA/Alemania/Frankfurt.png" },
    { id: "elversberg", nombre: "Elversberg", escudo: "UEFA/Alemania/Elversberg.png" },
    { id: "friburgo", nombre: "Friburgo", escudo: "UEFA/Alemania/Freiburg.png" },
    { id: "hamburgo", nombre: "Hamburgo", escudo: "UEFA/Alemania/Hamburger.png" },
    { id: "hoffenheim", nombre: "Hoffenheim", escudo: "UEFA/Alemania/Hoffenheim.png" },
    { id: "mainz-05", nombre: "Mainz 05", escudo: "UEFA/Alemania/Mainz.png" },
    { id: "paderborn", nombre: "Paderborn", escudo: "UEFA/Alemania/Paderborn.png" },
    { id: "rb-leipzig", nombre: "RB Leipzig", escudo: "UEFA/Alemania/Leipzig.png" },
    { id: "schalke-04", nombre: "Schalke 04", escudo: "UEFA/Alemania/Schalke.png" },
    { id: "stuttgart", nombre: "Stuttgart", escudo: "UEFA/Alemania/Stuttgart.png" },
    { id: "union-berlin", nombre: "Union Berlín", escudo: "UEFA/Alemania/Berlin.png" },
    { id: "werder-bremen", nombre: "Werder Bremen", escudo: "UEFA/Alemania/Werder.png" },
  ],
  "primera-division-espana": [
    { id: "alaves", nombre: "Alavés", escudo: "UEFA/España/Alaves.png" },
    { id: "athletic-bilbao", nombre: "Athletic Bilbao", escudo: "" },
    { id: "atletico-madrid", nombre: "Atlético Madrid", escudo: "UEFA/España/AtleticoMadrid.png" },
    { id: "barcelona", nombre: "Barcelona", escudo: "UEFA/España/Barcelona.png" },
    { id: "celta-vigo", nombre: "Celta Vigo", escudo: "UEFA/España/Celta.png" },
    { id: "deportivo-la-coruna", nombre: "Deportivo La Coruña", escudo: "UEFA/España/Coruña.png" },
    { id: "elche", nombre: "Elche", escudo: "UEFA/España/Elche.png" },
    { id: "espanyol", nombre: "Espanyol", escudo: "" },
    { id: "getafe", nombre: "Getafe", escudo: "UEFA/España/Getafe.png" },
    { id: "levante", nombre: "Levante", escudo: "UEFA/España/Levante.png" },
    { id: "malaga", nombre: "Málaga", escudo: "UEFA/España/Malaga.png" },
    { id: "osasuna", nombre: "Osasuna", escudo: "UEFA/España/Osasuna.png" },
    { id: "racing-santander", nombre: "Racing Santander", escudo: "UEFA/España/Santander.png" },
    { id: "rayo-vallecano", nombre: "Rayo Vallecano", escudo: "" },
    { id: "real-betis", nombre: "Real Betis", escudo: "" },
    { id: "real-madrid", nombre: "Real Madrid", escudo: "UEFA/España/RealMadrid.png" },
    { id: "real-sociedad", nombre: "Real Sociedad", escudo: "" },
    { id: "sevilla", nombre: "Sevilla", escudo: "UEFA/España/Sevilla.png" },
    { id: "valencia", nombre: "Valencia", escudo: "UEFA/España/Valencia.png" },
    { id: "villarreal", nombre: "Villarreal", escudo: "" },
  ],
  "serie-a-italia": [
    { id: "atalanta", nombre: "Atalanta", escudo: "UEFA/Italia/Atalanta.png" },
    { id: "bologna", nombre: "Bologna", escudo: "UEFA/Italia/Bologna.png" },
    { id: "cagliari", nombre: "Cagliari", escudo: "UEFA/Italia/Cagliari.png" },
    { id: "como", nombre: "Como", escudo: "UEFA/Italia/Como.png" },
    { id: "fiorentina", nombre: "Fiorentina", escudo: "UEFA/Italia/Fiorentina.png" },
    { id: "frosinone", nombre: "Frosinone", escudo: "UEFA/Italia/Frosinone.png" },
    { id: "genoa", nombre: "Genoa", escudo: "UEFA/Italia/Genoa.png" },
    { id: "inter", nombre: "Inter", escudo: "UEFA/Italia/Inter.png" },
    { id: "juventus", nombre: "Juventus", escudo: "UEFA/Italia/Juventus.png" },
    { id: "lazio", nombre: "Lazio", escudo: "UEFA/Italia/Lazio.png" },
    { id: "lecce", nombre: "Lecce", escudo: "UEFA/Italia/Lecce.png" },
    { id: "milan", nombre: "Milan", escudo: "UEFA/Italia/Milan.png" },
    { id: "monza", nombre: "Monza", escudo: "UEFA/Italia/Monza.png" },
    { id: "napoli", nombre: "Napoli", escudo: "UEFA/Italia/Napoli.png" },
    { id: "parma", nombre: "Parma", escudo: "" },
    { id: "roma", nombre: "Roma", escudo: "UEFA/Italia/Roma.png" },
    { id: "sassuolo", nombre: "Sassuolo", escudo: "UEFA/Italia/Sassuolo.png" },
    { id: "torino", nombre: "Torino", escudo: "UEFA/Italia/Torino.png" },
    { id: "udinese", nombre: "Udinese", escudo: "UEFA/Italia/Udinese.png" },
    { id: "venezia", nombre: "Venezia", escudo: "UEFA/Italia/Venezia.png" },
  ],
  "ligue-1-francia": [
    { id: "angers", nombre: "Angers", escudo: "UEFA/Francia/Angers.png" },
    { id: "auxerre", nombre: "Auxerre", escudo: "UEFA/Francia/Auxerre.png" },
    { id: "brest", nombre: "Brest", escudo: "UEFA/Francia/Brest.png" },
    { id: "estrasburgo", nombre: "Estrasburgo", escudo: "" },
    { id: "le-havre", nombre: "Le Havre", escudo: "UEFA/Francia/Havre.png" },
    { id: "le-mans", nombre: "Le Mans", escudo: "UEFA/Francia/Mans.png" },
    { id: "lens", nombre: "Lens", escudo: "UEFA/Francia/Lens.png" },
    { id: "lille", nombre: "Lille", escudo: "UEFA/Francia/Lille.png" },
    { id: "lorient", nombre: "Lorient", escudo: "UEFA/Francia/Lorient.png" },
    { id: "lyon", nombre: "Lyon", escudo: "UEFA/Francia/Lyon.png" },
    { id: "marsella", nombre: "Marsella", escudo: "" },
    { id: "monaco", nombre: "Mónaco", escudo: "UEFA/Francia/Monaco.png" },
    { id: "niza", nombre: "Niza", escudo: "UEFA/Francia/Nice.png" },
    { id: "paris-fc", nombre: "París FC", escudo: "UEFA/Francia/Paris.png" },
    { id: "psg", nombre: "PSG", escudo: "UEFA/Francia/PSG.png" },
    { id: "rennes", nombre: "Rennes", escudo: "UEFA/Francia/Rennes.png" },
    { id: "toulouse", nombre: "Toulouse", escudo: "UEFA/Francia/Toulouse.png" },
    { id: "troyes", nombre: "Troyes", escudo: "UEFA/Francia/Troyes.png" },
  ],
  "premier-league-inglaterra": [
    { id: "arsenal", nombre: "Arsenal", escudo: "UEFA/Inglaterra/Arsenal.png" },
    { id: "aston-villa", nombre: "Aston Villa", escudo: "UEFA/Inglaterra/Aston.png" },
    { id: "bournemouth", nombre: "Bournemouth", escudo: "" },
    { id: "brentford", nombre: "Brentford", escudo: "UEFA/Inglaterra/Brentford.png" },
    { id: "brighton", nombre: "Brighton", escudo: "UEFA/Inglaterra/Brighton.png" },
    { id: "chelsea", nombre: "Chelsea", escudo: "UEFA/Inglaterra/Chelsea.png" },
    { id: "coventry-city", nombre: "Coventry City", escudo: "UEFA/Inglaterra/Coventry.png" },
    { id: "crystal-palace", nombre: "Crystal Palace", escudo: "UEFA/Inglaterra/CrystalPalace.png" },
    { id: "everton", nombre: "Everton", escudo: "UEFA/Inglaterra/Everton.png" },
    { id: "fulham", nombre: "Fulham", escudo: "UEFA/Inglaterra/Fulham.png" },
    { id: "hull-city", nombre: "Hull City", escudo: "UEFA/Inglaterra/HullCity.png" },
    { id: "ipswich-town", nombre: "Ipswich Town", escudo: "UEFA/Inglaterra/Ipswich.png" },
    { id: "leeds-united", nombre: "Leeds United", escudo: "UEFA/Inglaterra/Leeds.png" },
    { id: "liverpool", nombre: "Liverpool", escudo: "UEFA/Inglaterra/Liverpool.png" },
    { id: "manchester-city", nombre: "Manchester City", escudo: "UEFA/Inglaterra/Mancity.png" },
    { id: "manchester-united", nombre: "Manchester United", escudo: "UEFA/Inglaterra/Manunited.png" },
    { id: "newcastle", nombre: "Newcastle", escudo: "UEFA/Inglaterra/Newcastle.png" },
    { id: "nottingham-forest", nombre: "Nottingham Forest", escudo: "UEFA/Inglaterra/Nottingham.png" },
    { id: "sunderland", nombre: "Sunderland", escudo: "UEFA/Inglaterra/Sunderland.png" },
    { id: "tottenham", nombre: "Tottenham", escudo: "UEFA/Inglaterra/Tottenham.png" },
  ],
};

/**
 * ESCUDOS Y BANDERAS
 * -----------------------------------------
 */