/* Minijuegos internacionales del Arquero. */

function resultadoArquero(contenedor,cabecera,exito,titulo,texto,callback){contenedor.innerHTML=`${cabecera}<div class="competition-card resultado-minijuego ${exito?"campeon":"subcampeon"}"><span class="resultado-minijuego__icono">${exito?"🧤":"🥅"}</span><h3>${titulo}</h3><p>${texto}</p><button class="boton-continuar">Continuar</button></div>`;contenedor.querySelector(".boton-continuar").onclick=()=>callback(exito);}

function minijuegoBarraArquero(callback,jugador,rival,dificultad=1,titulo="Bajo los tres palos"){const contenedor=document.getElementById("competition-container"),cabecera=crearCabeceraMinijuego(jugador,rival),ancho=Math.max(8,36-dificultad*4+(jugador.stats.reflejos||50)/4+(jugador.stats.velocidad||50)/8);let p=0,d=1,activo=false,loop;contenedor.innerHTML=`${cabecera}<div class="competition-card"><span class="badge-copa">LIBERTADORES</span><h3>${titulo}</h3><p>Frená el reflejo dentro de la zona de salvada.</p><div class="medidor-potencia medidor-arquero"><span class="zona-perfecta" style="left:${50-ancho/2}%;width:${ancho}%"></span><span class="cursor-potencia" id="cursor-arquero"></span></div><button class="boton-jugar-minijuego" id="atajar-barra">Preparar atajada</button></div>`;const cursor=contenedor.querySelector("#cursor-arquero"),btn=contenedor.querySelector("#atajar-barra");btn.onclick=()=>{if(!activo){activo=true;btn.textContent="¡ATAJAR!";const vel=1.5+dificultad*1.25;loop=setInterval(()=>{p+=d*vel;if(p>=100||p<=0)d*=-1;cursor.style.left=`${p}%`;},18);}else{clearInterval(loop);const ok=Math.abs(p-50)<=ancho/2;resultadoArquero(contenedor,cabecera,ok,ok?"¡Atajada imposible!":"No llegó",ok?"Volaste al ángulo y salvaste al equipo.":"La pelota encontró la red.",callback);}};}

function minijuegoCazarMariposas(callback,jugador,rival){const contenedor=document.getElementById("competition-container"),cabecera=crearCabeceraMinijuego(jugador,rival),margen=Math.min(40,15+(jugador.stats.juegoAereo||50)/4);let t=100,activo=false,loop;contenedor.innerHTML=`${cabecera}<div class="competition-card"><h3>Cazar mariposas</h3><p>Salí a cortar el córner en el punto exacto.</p><div class="duelo-aereo"><span class="circulo-objetivo" style="width:${margen}%;height:${margen}%"></span><span class="circulo-timing" id="circulo-arquero"></span></div><button class="boton-jugar-minijuego" id="salir-corner">Salir del arco</button></div>`;const circ=contenedor.querySelector("#circulo-arquero"),btn=contenedor.querySelector("#salir-corner");btn.onclick=()=>{if(!activo){activo=true;btn.textContent="¡SALIR!";loop=setInterval(()=>{t-=1.9;circ.style.width=`${t}%`;circ.style.height=`${t}%`;if(t<=0){clearInterval(loop);resultadoArquero(contenedor,cabecera,false,"Centro pasado","No llegaste a descolgar la pelota.",callback);}},18);}else{clearInterval(loop);const ok=Math.abs(t-margen)<=margen/2;resultadoArquero(contenedor,cabecera,ok,ok?"¡Se quedó con todo!":"Calculó mal",ok?"Dominaste el área y apagaste el peligro.":"El centro quedó servido para el rival.",callback);}};}

function minijuegoManoAMano(callback,jugador,rival){const contenedor=document.getElementById("competition-container"),cabecera=crearCabeceraMinijuego(jugador,rival),dirs=["⬅", "⬆", "➡"],disponibles=[0,1,2],secuencia=Array.from({length:3},()=>disponibles.splice(Math.floor(Math.random()*disponibles.length),1)[0]);let entrada=[];contenedor.innerHTML=`${cabecera}<div class="competition-card"><h3>El mano a mano</h3><p>Leé el perfil del delantero y achicá en el orden correcto.</p><div class="qte-secuencia" id="visor-mano">● ● ●</div><div class="teclas-qte" id="teclas-mano"></div><button class="boton-jugar-minijuego" id="mostrar-mano">Leer la jugada</button></div>`;const visor=contenedor.querySelector("#visor-mano"),zona=contenedor.querySelector("#teclas-mano"),ver=contenedor.querySelector("#mostrar-mano");dirs.forEach((dir,i)=>zona.insertAdjacentHTML("beforeend",`<button class="tecla-qte" disabled data-i="${i}">${dir}</button>`));const botones=[...zona.children];ver.onclick=()=>{ver.hidden=true;let p=0;const loop=setInterval(()=>{visor.textContent=secuencia.slice(0,p+1).map(x=>dirs[x]).join(" ");if(++p===3){clearInterval(loop);setTimeout(()=>{visor.textContent="Elegí el achique";botones.forEach(b=>b.disabled=false);},450);}},420);};botones.forEach(b=>b.onclick=()=>{entrada.push(+b.dataset.i);b.disabled=true;if(entrada.length===3){const ok=entrada.every((x,i)=>x===secuencia[i]);resultadoArquero(contenedor,cabecera,ok,ok?"¡Gigante!":"Te cruzó el remate",ok?"Achicaste perfecto y tapaste con el cuerpo.":"El delantero encontró el hueco.",callback);}});}

function minijuegoDobleAtajada(callback,jugador,rival){const contenedor=document.getElementById("competition-container"),cabecera=crearCabeceraMinijuego(jugador,rival);contenedor.innerHTML=`${cabecera}<div class="competition-card"><h3>Doble atajada</h3><p>Primero frená el remate. Después, reaccioná al rebote.</p><button class="boton-jugar-minijuego" id="primera-atajada">Atajar primer tiro</button><div class="zona-rebote" id="zona-rebote"></div></div>`;const primer=contenedor.querySelector("#primera-atajada"),zona=contenedor.querySelector("#zona-rebote");primer.onclick=()=>{primer.hidden=true;setTimeout(()=>{const btn=document.createElement("button");btn.className="alerta-cierre activo";btn.textContent="¡REBOTE!";btn.style.left=`${15+Math.random()*60}%`;zona.append(btn);const limite=setTimeout(()=>resultadoArquero(contenedor,cabecera,false,"Rebote fatal","La segunda pelota terminó en gol.",callback),Math.max(450,1100-(jugador.stats.reflejos||50)*6));btn.onclick=()=>{clearTimeout(limite);resultadoArquero(contenedor,cabecera,true,"Doble atajada","Volviste del piso para salvar un gol imposible.",callback);};},500);};}

function jugarLibertadoresArquero(callback,jugador,rival){let ronda=1;const fases=["Fase de Grupos","Fase de Grupos","Fase de Grupos","Octavos de final","Cuartos de final","Semifinal","Final"];const seguir=ok=>{if(!ok)return callback(false,fases[ronda-1]);if(ronda++===7)return callback(true);minijuegoBarraArquero(seguir,jugador,rival,ronda);};minijuegoBarraArquero(seguir,jugador,rival,ronda);}
function jugarSudamericanaArquero(callback,jugador,rival){minijuegoCazarMariposas(ok=>ok?minijuegoManoAMano(callback,jugador,rival):callback(false),jugador,rival);}
function jugarRecopaArquero(callback,jugador,rival){minijuegoDobleAtajada(ok=>ok?minijuegoBarraArquero(callback,jugador,rival,7,"El penal del campeonato"):callback(false),jugador,rival);}
