/* Minijuegos internacionales del Defensor Central. */

function resultadoCentral(contenedor, cabecera, exito, titulo, texto, callback) {
  contenedor.innerHTML = `${cabecera}<div class="competition-card resultado-minijuego ${exito ? "campeon" : "subcampeon"}"><span class="resultado-minijuego__icono">${exito ? "🛡️" : "💥"}</span><h3>${titulo}</h3><p>${texto}</p><button class="boton-continuar">Continuar</button></div>`;
  contenedor.querySelector(".boton-continuar").onclick = () => callback(exito);
}

function minijuegoDueloAereo(callback, jugador, rival, dificultad = 1, titulo = "Duelo aéreo constante") {
  const contenedor = document.getElementById("competition-container"), cabecera = crearCabeceraMinijuego(jugador, rival);
  const margen = Math.min(42, 14 + ((jugador.stats.resistencia || 50) + (jugador.stats.liderazgo || 50)) / 6); let ganados = 0, ronda = 0, activo = false;
  contenedor.innerHTML = `${cabecera}<div class="competition-card"><span class="badge-copa">LIBERTADORES</span><h3>${titulo}</h3><p>Frená el círculo cuando llegue a la zona de impacto. Ganá 2 de 3.</p><div class="duelo-aereo"><span class="circulo-objetivo" style="width:${margen}%;height:${margen}%"></span><span class="circulo-timing" id="circulo-timing"></span></div><div class="estado-minijuego" id="estado-aereo">Duelos ganados: 0/2</div><button class="boton-jugar-minijuego" id="saltar-aereo">Saltar</button></div>`;
  const circulo = contenedor.querySelector("#circulo-timing"), boton = contenedor.querySelector("#saltar-aereo"), estado = contenedor.querySelector("#estado-aereo"); let tamano = 100, loop;
  function iniciar() { activo = true; boton.textContent = "¡Cabezazo!"; tamano = 100; const velocidad = 1.15 + dificultad * .75; loop = setInterval(() => { tamano -= velocidad; circulo.style.width = `${Math.max(0, tamano)}%`; circulo.style.height = `${Math.max(0, tamano)}%`; if (tamano <= 0) resolver(false); }, 18); }
  function resolver(acierto) { clearInterval(loop); activo = false; ronda++; if(acierto) ganados++; estado.textContent = `Duelos ganados: ${ganados}/2 · Intento ${ronda}/3`; if(ganados >= 2) return resultadoCentral(contenedor,cabecera,true,"Ganaste arriba","No pudieron con tu presencia en el área.",callback); if(ronda === 3) return resultadoCentral(contenedor,cabecera,false,"Centro venenoso","El rival ganó el último duelo.",callback); boton.textContent="Siguiente centro"; }
  boton.onclick = () => { if (!activo) iniciar(); else { const acierto = Math.abs(tamano - margen) <= margen / 2; resolver(acierto); } };
}

function minijuegoCierreProvidencial(callback, jugador, rival) {
  const contenedor=document.getElementById("competition-container"), cabecera=crearCabeceraMinijuego(jugador,rival); let resuelto=false;
  contenedor.innerHTML=`${cabecera}<div class="competition-card"><h3>Cierre providencial</h3><p>El delantero quedó mano a mano. Esperá la señal y tocá ¡AHORA!.</p><button class="alerta-cierre" id="alerta-cierre" disabled>ESPERÁ…</button></div>`;
  const boton=contenedor.querySelector("#alerta-cierre"); setTimeout(()=>{boton.disabled=false;boton.textContent="¡AHORA!";boton.classList.add("activo");const limite=setTimeout(()=>{if(!resuelto){resuelto=true;resultadoCentral(contenedor,cabecera,false,"Llegaste tarde","El delantero definió antes de tu barrida.",callback);}}, Math.max(350,850-(jugador.stats.velocidad||50)*5));boton.onclick=()=>{if(resuelto)return;resuelto=true;clearTimeout(limite);resultadoCentral(contenedor,cabecera,true,"Barrida limpia","Le sacaste la pelota justo a tiempo.",callback);};},500+Math.random()*800);
}

function minijuegoDespejeLinea(callback, jugador, rival) {
  const contenedor=document.getElementById("competition-container"), cabecera=crearCabeceraMinijuego(jugador,rival), ancho=Math.min(34,12+(jugador.stats.quite||50)/4);let p=0,d=1,corriendo=false,loop;
  contenedor.innerHTML=`${cabecera}<div class="competition-card"><h3>Despeje en la línea</h3><p>Frená el cursor en la zona segura para reventarla lejos.</p><div class="medidor-potencia"><span class="zona-perfecta" style="left:${50-ancho/2}%;width:${ancho}%"></span><span class="cursor-potencia" id="cursor-linea"></span></div><button class="boton-jugar-minijuego" id="accion-linea">Prepararse</button></div>`;
  const cursor=contenedor.querySelector("#cursor-linea"),btn=contenedor.querySelector("#accion-linea");btn.onclick=()=>{if(!corriendo){corriendo=true;btn.textContent="¡Despejar!";loop=setInterval(()=>{p+=d*3;if(p>=100||p<=0)d*=-1;cursor.style.left=`${p}%`;},20);}else{clearInterval(loop);const ok=Math.abs(p-50)<=ancho/2;resultadoCentral(contenedor,cabecera,ok,ok?"¡La sacaste!":"Gol sobre la línea",ok?"El estadio quedó mudo con tu despeje.":"La pelota cruzó antes de que llegaras.",callback);}};
}

function minijuegoOffside(callback,jugador,rival){const contenedor=document.getElementById("competition-container"),cabecera=crearCabeceraMinijuego(jugador,rival),objetivo=Math.floor(Math.random()*4);contenedor.innerHTML=`${cabecera}<div class="competition-card"><h3>Trampa del offside</h3><p>Memorizá quién pica al vacío y ordená la línea.</p><div class="offside-rivales" id="offside-rivales"></div><button class="boton-jugar-minijuego" id="ver-offside">Ver movimiento</button></div>`;const zona=contenedor.querySelector("#offside-rivales"),ver=contenedor.querySelector("#ver-offside");for(let i=0;i<4;i++)zona.insertAdjacentHTML("beforeend",`<button class="rival-offside" data-i="${i}">Rival ${i+1}</button>`);const botones=[...zona.children];botones.forEach(b=>b.disabled=true);ver.onclick=()=>{ver.hidden=true;botones[objetivo].classList.add("pica");setTimeout(()=>{botones[objetivo].classList.remove("pica");botones.forEach(b=>b.disabled=false);},650);};botones.forEach(b=>b.onclick=()=>{const ok=+b.dataset.i===objetivo;resultadoCentral(contenedor,cabecera,ok,ok?"Fuera de juego":"Línea rota",ok?"Tu orden dejó al rival adelantado.":"El delantero recibió habilitado.",callback);});}

function minijuegoCuerpoACuerpo(callback,jugador,rival){const contenedor=document.getElementById("competition-container"),cabecera=crearCabeceraMinijuego(jugador,rival);let golpes=0,activo=false;contenedor.innerHTML=`${cabecera}<div class="competition-card"><h3>Cuerpo a cuerpo</h3><p>Presioná 10 veces antes de que termine el forcejeo.</p><div class="contador-fuerza" id="contador-fuerza">0 / 10</div><button class="boton-fuerza" id="boton-fuerza">AGUANTAR</button></div>`;const boton=contenedor.querySelector("#boton-fuerza"),contador=contenedor.querySelector("#contador-fuerza");boton.onclick=()=>{if(!activo){activo=true;boton.textContent="¡METÉ!";setTimeout(()=>{if(golpes<10)resultadoCentral(contenedor,cabecera,false,"Te ganó la posición","El tanque rival alcanzó a conectar el centro.",callback);},2100);return;}golpes++;contador.textContent=`${golpes} / 10`;if(golpes>=10)resultadoCentral(contenedor,cabecera,true,"Choque ganado","Aguantaste la marca y rechazaste lejos.",callback);};}

function jugarLibertadoresCentral(callback,jugador,rival){let ronda=1;const fases=["Fase de Grupos · Partido 1","Fase de Grupos · Partido 2","Fase de Grupos · Partido 3","Octavos de final","Cuartos de final","Semifinal","Final"];const jugarRonda=()=>{const rivalActual=ronda===1?rival:obtenerRivalInternacional(jugador);window.CONTEXTO_PARTIDO={torneo:"Copa Libertadores",fase:fases[ronda-1]};minijuegoDueloAereo(seguir,jugador,rivalActual,ronda);};const seguir=ok=>{if(!ok)return callback(false,fases[ronda-1]);if(ronda++===7)return callback(true);jugarRonda();};jugarRonda();}
function jugarSudamericanaCentral(callback,jugador,rival){minijuegoCierreProvidencial(ok=>ok?minijuegoDespejeLinea(callback,jugador,rival):callback(false),jugador,rival);}
function jugarRecopaCentral(callback,jugador,rival){minijuegoOffside(ok=>ok?minijuegoCuerpoACuerpo(callback,jugador,rival):callback(false),jugador,rival);}
